export default {
    "data": {
        "pending_availibility": [],
        "available": [
            {
                "id": 99,
                "po_num": null,
                "mbl_num": "MBL",
                "type": null,
                "term": null,
                "customer_id": 18,
                "delivery_order_id": 2,
                "shipment_status": null,
                "shifl_ref": "700099",
                "origin_country": null,
                "destination_country": null,
                "etd": null,
                "eta": "2022-09-13T00:00:00.000000Z",
                "custom_notes": "fff",
                "total_cbm": null,
                "total_kg": null,
                "total_cartons": null,
                "created_at": "2022-09-13T20:34:14.000000Z",
                "updated_at": "2022-10-07T14:36:50.000000Z",
                "carrier_id": 4,
                "custom_content": null,
                "suppliers_group": null,
                "schedules_group": null,
                "containers_group": null,
                "mbl_copy": null,
                "debit_note": null,
                "vessel": "V123",
                "booking_confirmed": 0,
                "arrival_notice_confirmed": 0,
                "freight_released_processed": 0,
                "customs_processed": 0,
                "DO_confirmed": 0,
                "freight_confirmed": 0,
                "customs_released": 0,
                "pending_refund": 0,
                "delivered": 0,
                "billed": 0,
                "cancelled": 0,
                "shipment_left": 0,
                "terminal_id": 9,
                "arrival_notice": 0,
                "cloned_from": null,
                "trucker_id": 2,
                "trucker_custom_note": null,
                "delivery_order_left": 0,
                "copy_customer": 1,
                "memo_customer": null,
                "suppliers_group_bookings": null,
                "containers_group_bookings": null,
                "schedules_group_bookings": null,
                "mbl_shipper": null,
                "mbl_shipper_address": null,
                "mbl_shipper_phone_number": null,
                "mbl_consignee": null,
                "mbl_consignee_address": null,
                "mbl_consignee_phone_number": null,
                "mbl_notify": null,
                "mbl_notify_address": null,
                "mbl_notify_phone_number": null,
                "mbl_description": null,
                "mbl_marks": null,
                "booking_confirmed_at": null,
                "tracking_request_id": null,
                "entry_netchb_submitted": 0,
                "entry_netchb_no": null,
                "entry_netchb_date": null,
                "entry_data": null,
                "do_sent_at": null,
                "an_sent_at": null,
                "retry_tracking_request": 0,
                "suppliers_commercial_docs": null,
                "pier_pass_paid": 1,
                "discharged": 1,
                "driver_assigned_pickup": 1,
                "container_empty": 0,
                "container_empty_time": null,
                "container_empty_date": null,
                "asigned_driver_return": 0,
                "returned": 0,
                "trucker_container": "container",
                "deliver_to": "11",
                "dispatch_schedule": "{\"location_from\":9,\"legs\":[{\"id\":1665124572029,\"type\":\"Customer\",\"address\":\"Porbandar, Gujarat, India\",\"date\":\"2022-10-11\",\"time\":\"23:27\",\"driver\":94,\"chassis\":7,\"mode\":\"Dropped\",\"completed\":false,\"from_date\":\"2022-10-08\",\"to_time\":\"12:56\",\"arrival_at_pickup_location_date\":\"\",\"arrival_at_pickup_location_time\":\"\",\"departure_from_pickup_location_date\":\"\",\"departure_from_pickup_location_time\":\"\",\"arrival_at_delivery_location_date\":\"\",\"arrival_at_delivery_location_time\":\"\",\"departure_from_delivery_location_date\":\"\",\"departure_from_delivery_location_time\":\"\"}],\"last_free_date\":\"2022-10-12\",\"per_diem_date\":\"2022-10-20\"}",
                "container_weight": "11.00",
                "container_size_id": 1,
                "container_commodity": "ffff",
                "customer_po": "C123",
                "last_free_date": "2022-10-12T00:00:00.000000Z",
                "dropped": 0,
                "fully_released": 1,
                "arrived": 0,
                "dropped_full": 0,
                "dropped_empty": 0,
                "pending_billing": 0,
                "completed": 0,
                "in_yard_full": 0,
                "container_type_id": 0,
                "address": null,
                "per_diem_date": "2022-10-20",
                "contacts": "[\"test123@gmail.com\"]",
                "is_scheduled": 1,
                "container_size": {
                    "id": 1,
                    "name": "20",
                    "created_at": "2021-05-30T22:29:59.000000Z",
                    "updated_at": "2021-05-30T22:29:59.000000Z",
                    "length": null,
                    "width": null,
                    "height": null,
                    "dimension": null
                },
                "terminal": {
                    "id": 9,
                    "name": "Everport Terminal - Berth 233 (Y124)",
                    "firms_code": "Y124",
                    "address": "389 Terminal Way, San Pedro, CA 90731",
                    "created_at": "2020-04-22T06:06:58.000000Z",
                    "updated_at": "2022-02-15T05:59:49.000000Z",
                    "gate_fee": 1,
                    "map_location": null,
                    "latitude": null,
                    "longitude": null
                },
                "customer": {
                    "id": 18,
                    "company_name": "Vivekcustomerty",
                    "address": null,
                    "phone": "1234567890",
                    "admin_user_id": null,
                    "created_at": "2022-08-12T19:14:37.000000Z",
                    "updated_at": "2022-08-30T05:01:23.000000Z",
                    "managers": null,
                    "sale_persons": null,
                    "emails": [
                        {
                            "email": "vivek@gmail.com"
                        }
                    ],
                    "requirements": null,
                    "credit_term_freight": null,
                    "ein": null,
                    "trucker_id": 2,
                    "delivery_address": null,
                    "central_customer_key": "MFBQW8ZB"
                },
                "carrier": null,
                "dispatch": {
                    "id": 74,
                    "unique_id": null,
                    "shipment_id": 99,
                    "terminal_id": 9,
                    "last_free_date": "2022-10-12",
                    "per_diem_date": "2022-10-20",
                    "created_at": "2022-09-16T04:30:42.000000Z",
                    "updated_at": "2022-10-07T14:36:50.000000Z",
                    "legs": [
                        {
                            "id": 63,
                            "unique_id": "1665124572029",
                            "schedule_unique_id": null,
                            "is_first_leg": 1,
                            "type": "Customer",
                            "mode": "Dropped",
                            "address": "Porbandar, Gujarat, India",
                            "pickup_location": null,
                            "chassis_id": 7,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 74,
                            "completed": 0,
                            "pickup_scheduled_date_time": "2022-10-08 12:56:00",
                            "arrival_at_pickup_location_date_time": null,
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-10-11 23:27:00",
                            "arrival_at_delivery_location_date_time": null,
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-10-07T14:36:50.000000Z",
                            "updated_at": null
                        }
                    ]
                }
            }
        ],
        "in_yard_full": [],
        "scheduled": [
            {
                "id": 99,
                "po_num": null,
                "mbl_num": "MBL",
                "type": null,
                "term": null,
                "customer_id": 18,
                "delivery_order_id": 2,
                "shipment_status": null,
                "shifl_ref": "700099",
                "origin_country": null,
                "destination_country": null,
                "etd": null,
                "eta": "2022-09-13T00:00:00.000000Z",
                "custom_notes": "fff",
                "total_cbm": null,
                "total_kg": null,
                "total_cartons": null,
                "created_at": "2022-09-13T20:34:14.000000Z",
                "updated_at": "2022-10-07T14:36:50.000000Z",
                "carrier_id": 4,
                "custom_content": null,
                "suppliers_group": null,
                "schedules_group": null,
                "containers_group": null,
                "mbl_copy": null,
                "debit_note": null,
                "vessel": "V123",
                "booking_confirmed": 0,
                "arrival_notice_confirmed": 0,
                "freight_released_processed": 0,
                "customs_processed": 0,
                "DO_confirmed": 0,
                "freight_confirmed": 0,
                "customs_released": 0,
                "pending_refund": 0,
                "delivered": 0,
                "billed": 0,
                "cancelled": 0,
                "shipment_left": 0,
                "terminal_id": 9,
                "arrival_notice": 0,
                "cloned_from": null,
                "trucker_id": 2,
                "trucker_custom_note": null,
                "delivery_order_left": 0,
                "copy_customer": 1,
                "memo_customer": null,
                "suppliers_group_bookings": null,
                "containers_group_bookings": null,
                "schedules_group_bookings": null,
                "mbl_shipper": null,
                "mbl_shipper_address": null,
                "mbl_shipper_phone_number": null,
                "mbl_consignee": null,
                "mbl_consignee_address": null,
                "mbl_consignee_phone_number": null,
                "mbl_notify": null,
                "mbl_notify_address": null,
                "mbl_notify_phone_number": null,
                "mbl_description": null,
                "mbl_marks": null,
                "booking_confirmed_at": null,
                "tracking_request_id": null,
                "entry_netchb_submitted": 0,
                "entry_netchb_no": null,
                "entry_netchb_date": null,
                "entry_data": null,
                "do_sent_at": null,
                "an_sent_at": null,
                "retry_tracking_request": 0,
                "suppliers_commercial_docs": null,
                "pier_pass_paid": 1,
                "discharged": 1,
                "driver_assigned_pickup": 1,
                "container_empty": 0,
                "container_empty_time": null,
                "container_empty_date": null,
                "asigned_driver_return": 0,
                "returned": 0,
                "trucker_container": "container",
                "deliver_to": "11",
                "dispatch_schedule": "{\"location_from\":9,\"legs\":[{\"id\":1665124572029,\"type\":\"Customer\",\"address\":\"Porbandar, Gujarat, India\",\"date\":\"2022-10-11\",\"time\":\"23:27\",\"driver\":94,\"chassis\":7,\"mode\":\"Dropped\",\"completed\":false,\"from_date\":\"2022-10-08\",\"to_time\":\"12:56\",\"arrival_at_pickup_location_date\":\"\",\"arrival_at_pickup_location_time\":\"\",\"departure_from_pickup_location_date\":\"\",\"departure_from_pickup_location_time\":\"\",\"arrival_at_delivery_location_date\":\"\",\"arrival_at_delivery_location_time\":\"\",\"departure_from_delivery_location_date\":\"\",\"departure_from_delivery_location_time\":\"\"}],\"last_free_date\":\"2022-10-12\",\"per_diem_date\":\"2022-10-20\"}",
                "container_weight": "11.00",
                "container_size_id": 1,
                "container_commodity": "ffff",
                "customer_po": "C123",
                "last_free_date": "2022-10-12T00:00:00.000000Z",
                "dropped": 0,
                "fully_released": 1,
                "arrived": 0,
                "dropped_full": 0,
                "dropped_empty": 0,
                "pending_billing": 0,
                "completed": 0,
                "in_yard_full": 0,
                "container_type_id": 0,
                "address": null,
                "per_diem_date": "2022-10-20",
                "contacts": "[\"test123@gmail.com\"]",
                "is_scheduled": 1,
                "container_size": {
                    "id": 1,
                    "name": "20",
                    "created_at": "2021-05-30T22:29:59.000000Z",
                    "updated_at": "2021-05-30T22:29:59.000000Z",
                    "length": null,
                    "width": null,
                    "height": null,
                    "dimension": null
                },
                "terminal": {
                    "id": 9,
                    "name": "Everport Terminal - Berth 233 (Y124)",
                    "firms_code": "Y124",
                    "address": "389 Terminal Way, San Pedro, CA 90731",
                    "created_at": "2020-04-22T06:06:58.000000Z",
                    "updated_at": "2022-02-15T05:59:49.000000Z",
                    "gate_fee": 1,
                    "map_location": null,
                    "latitude": null,
                    "longitude": null
                },
                "customer": {
                    "id": 18,
                    "company_name": "Vivekcustomerty",
                    "address": null,
                    "phone": "1234567890",
                    "admin_user_id": null,
                    "created_at": "2022-08-12T19:14:37.000000Z",
                    "updated_at": "2022-08-30T05:01:23.000000Z",
                    "managers": null,
                    "sale_persons": null,
                    "emails": [
                        {
                            "email": "vivek@gmail.com"
                        }
                    ],
                    "requirements": null,
                    "credit_term_freight": null,
                    "ein": null,
                    "trucker_id": 2,
                    "delivery_address": null,
                    "central_customer_key": "MFBQW8ZB"
                },
                "carrier": null,
                "dispatch": {
                    "id": 74,
                    "unique_id": null,
                    "shipment_id": 99,
                    "terminal_id": 9,
                    "last_free_date": "2022-10-12",
                    "per_diem_date": "2022-10-20",
                    "created_at": "2022-09-16T04:30:42.000000Z",
                    "updated_at": "2022-10-07T14:36:50.000000Z",
                    "legs": [
                        {
                            "id": 63,
                            "unique_id": "1665124572029",
                            "schedule_unique_id": null,
                            "is_first_leg": 1,
                            "type": "Customer",
                            "mode": "Dropped",
                            "address": "Porbandar, Gujarat, India",
                            "pickup_location": null,
                            "chassis_id": 7,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 74,
                            "completed": 0,
                            "pickup_scheduled_date_time": "2022-10-08 12:56:00",
                            "arrival_at_pickup_location_date_time": null,
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-10-11 23:27:00",
                            "arrival_at_delivery_location_date_time": null,
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-10-07T14:36:50.000000Z",
                            "updated_at": null
                        }
                    ]
                }
            }
        ],
        "at_the_customer": [],
        "dropped_empty": [],
        "pending_billing": [
            {
                "id": 93,
                "po_num": null,
                "mbl_num": "MBL123",
                "type": null,
                "term": null,
                "customer_id": 18,
                "delivery_order_id": null,
                "shipment_status": null,
                "shifl_ref": "700093",
                "origin_country": null,
                "destination_country": null,
                "etd": null,
                "eta": "2022-08-25T00:00:00.000000Z",
                "custom_notes": null,
                "total_cbm": null,
                "total_kg": null,
                "total_cartons": null,
                "created_at": "2022-08-24T13:48:55.000000Z",
                "updated_at": "2022-08-24T15:32:19.000000Z",
                "carrier_id": 4,
                "custom_content": null,
                "suppliers_group": null,
                "schedules_group": null,
                "containers_group": null,
                "mbl_copy": null,
                "debit_note": null,
                "vessel": "V123",
                "booking_confirmed": 0,
                "arrival_notice_confirmed": 0,
                "freight_released_processed": 0,
                "customs_processed": 0,
                "DO_confirmed": 0,
                "freight_confirmed": 0,
                "customs_released": 0,
                "pending_refund": 0,
                "delivered": 0,
                "billed": 0,
                "cancelled": 0,
                "shipment_left": 0,
                "terminal_id": 9,
                "arrival_notice": 0,
                "cloned_from": null,
                "trucker_id": 2,
                "trucker_custom_note": null,
                "delivery_order_left": 0,
                "copy_customer": 1,
                "memo_customer": null,
                "suppliers_group_bookings": null,
                "containers_group_bookings": null,
                "schedules_group_bookings": null,
                "mbl_shipper": null,
                "mbl_shipper_address": null,
                "mbl_shipper_phone_number": null,
                "mbl_consignee": null,
                "mbl_consignee_address": null,
                "mbl_consignee_phone_number": null,
                "mbl_notify": null,
                "mbl_notify_address": null,
                "mbl_notify_phone_number": null,
                "mbl_description": null,
                "mbl_marks": null,
                "booking_confirmed_at": null,
                "tracking_request_id": null,
                "entry_netchb_submitted": 0,
                "entry_netchb_no": null,
                "entry_netchb_date": null,
                "entry_data": null,
                "do_sent_at": null,
                "an_sent_at": null,
                "retry_tracking_request": 0,
                "suppliers_commercial_docs": null,
                "pier_pass_paid": 1,
                "discharged": 1,
                "driver_assigned_pickup": 0,
                "container_empty": 0,
                "container_empty_time": null,
                "container_empty_date": null,
                "asigned_driver_return": 0,
                "returned": 0,
                "trucker_container": "C123445",
                "deliver_to": "Rajkot",
                "dispatch_schedule": "{\"legs\":[{\"id\":1661320648280,\"type\":\"Yard\",\"address\":\"NY yard\",\"date\":\"2022-08-27\",\"time\":\"09:00\",\"driver\":94,\"chassis\":17,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-08-26\",\"to_time\":\"09:00\",\"arrival_at_pickup_location_date\":\"2022-08-26\",\"arrival_at_pickup_location_time\":\"10:00\",\"departure_from_pickup_location_date\":null,\"departure_from_pickup_location_time\":null,\"arrival_at_delivery_location_date\":\"2022-08-27\",\"arrival_at_delivery_location_time\":\"11:00\",\"departure_from_delivery_location_date\":null,\"departure_from_delivery_location_time\":null,\"address_from\":\"Everport Terminal - Berth 233 (Y124)\"},{\"id\":1661325808084,\"type\":\"Customer\",\"address\":\"Customer warehouse\",\"date\":\"2022-08-29\",\"time\":\"09:00\",\"driver\":94,\"chassis\":17,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-08-28\",\"to_time\":\"09:00\",\"arrival_at_pickup_location_date\":\"2022-08-28\",\"arrival_at_pickup_location_time\":\"10:00\",\"departure_from_pickup_location_date\":null,\"departure_from_pickup_location_time\":null,\"arrival_at_delivery_location_date\":\"2022-08-29\",\"arrival_at_delivery_location_time\":\"10:00\",\"departure_from_delivery_location_date\":null,\"departure_from_delivery_location_time\":null,\"address_from\":\"Everport Terminal - Berth 233 (Y124)\"},{\"id\":1661326259024,\"type\":\"Empty Return\",\"address\":\"Back to port\",\"date\":\"2022-08-31\",\"time\":\"09:00\",\"driver\":94,\"chassis\":17,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-08-30\",\"to_time\":\"09:00\",\"arrival_at_pickup_location_date\":\"2022-08-30\",\"arrival_at_pickup_location_time\":\"10:00\",\"departure_from_pickup_location_date\":\"\",\"departure_from_pickup_location_time\":\"\",\"arrival_at_delivery_location_date\":\"2022-08-31\",\"arrival_at_delivery_location_time\":\"10:00\",\"departure_from_delivery_location_date\":\"\",\"departure_from_delivery_location_time\":\"\",\"address_from\":\"Everport Terminal - Berth 233 (Y124)\"}],\"location_from\":9,\"per_diem_date\":\"2022-09-30\"}",
                "container_weight": "555.00",
                "container_size_id": 2,
                "container_commodity": "Iron",
                "customer_po": "PO123",
                "last_free_date": null,
                "dropped": 0,
                "fully_released": 1,
                "arrived": 1,
                "dropped_full": 0,
                "dropped_empty": 0,
                "pending_billing": 1,
                "completed": 0,
                "in_yard_full": 0,
                "container_type_id": 0,
                "address": null,
                "per_diem_date": "2022-09-30",
                "contacts": "[\"viveksamani47@gmail.com\"]",
                "is_scheduled": 1,
                "container_size": {
                    "id": 2,
                    "name": "40",
                    "created_at": "2021-05-30T22:30:12.000000Z",
                    "updated_at": "2021-05-30T22:30:12.000000Z",
                    "length": null,
                    "width": null,
                    "height": null,
                    "dimension": null
                },
                "terminal": {
                    "id": 9,
                    "name": "Everport Terminal - Berth 233 (Y124)",
                    "firms_code": "Y124",
                    "address": "389 Terminal Way, San Pedro, CA 90731",
                    "created_at": "2020-04-22T06:06:58.000000Z",
                    "updated_at": "2022-02-15T05:59:49.000000Z",
                    "gate_fee": 1,
                    "map_location": null,
                    "latitude": null,
                    "longitude": null
                },
                "customer": {
                    "id": 18,
                    "company_name": "Vivekcustomerty",
                    "address": null,
                    "phone": "1234567890",
                    "admin_user_id": null,
                    "created_at": "2022-08-12T19:14:37.000000Z",
                    "updated_at": "2022-08-30T05:01:23.000000Z",
                    "managers": null,
                    "sale_persons": null,
                    "emails": [
                        {
                            "email": "vivek@gmail.com"
                        }
                    ],
                    "requirements": null,
                    "credit_term_freight": null,
                    "ein": null,
                    "trucker_id": 2,
                    "delivery_address": null,
                    "central_customer_key": "MFBQW8ZB"
                },
                "carrier": null,
                "dispatch": {
                    "id": 68,
                    "unique_id": null,
                    "shipment_id": 93,
                    "terminal_id": 9,
                    "last_free_date": null,
                    "per_diem_date": "2022-09-30",
                    "created_at": "2022-09-16T04:30:42.000000Z",
                    "updated_at": "2022-09-16T04:30:42.000000Z",
                    "legs": [
                        {
                            "id": 53,
                            "unique_id": "1661320648280",
                            "schedule_unique_id": null,
                            "is_first_leg": 1,
                            "type": "Yard",
                            "mode": "Dropped",
                            "address": "NY yard",
                            "pickup_location": null,
                            "chassis_id": 17,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 68,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-08-26 09:00:00",
                            "arrival_at_pickup_location_date_time": "2022-08-26 10:00:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-08-27 09:00:00",
                            "arrival_at_delivery_location_date_time": "2022-08-27 11:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        },
                        {
                            "id": 54,
                            "unique_id": "1661325808084",
                            "schedule_unique_id": null,
                            "is_first_leg": 0,
                            "type": "Customer",
                            "mode": "Dropped",
                            "address": "Customer warehouse",
                            "pickup_location": "NY yard",
                            "chassis_id": 17,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 68,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-08-28 09:00:00",
                            "arrival_at_pickup_location_date_time": "2022-08-28 10:00:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-08-29 09:00:00",
                            "arrival_at_delivery_location_date_time": "2022-08-29 10:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        },
                        {
                            "id": 55,
                            "unique_id": "1661326259024",
                            "schedule_unique_id": null,
                            "is_first_leg": 0,
                            "type": "Empty Return",
                            "mode": "Dropped",
                            "address": "Back to port",
                            "pickup_location": "Customer warehouse",
                            "chassis_id": 17,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 68,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-08-30 09:00:00",
                            "arrival_at_pickup_location_date_time": "2022-08-30 10:00:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-08-31 09:00:00",
                            "arrival_at_delivery_location_date_time": "2022-08-31 10:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        }
                    ]
                }
            },
            {
                "id": 96,
                "po_num": null,
                "mbl_num": "MBL123",
                "type": null,
                "term": null,
                "customer_id": 18,
                "delivery_order_id": null,
                "shipment_status": null,
                "shifl_ref": "700096",
                "origin_country": null,
                "destination_country": null,
                "etd": null,
                "eta": "2022-09-05T00:00:00.000000Z",
                "custom_notes": null,
                "total_cbm": null,
                "total_kg": null,
                "total_cartons": null,
                "created_at": "2022-09-02T15:25:34.000000Z",
                "updated_at": "2022-09-02T17:30:45.000000Z",
                "carrier_id": 2,
                "custom_content": null,
                "suppliers_group": null,
                "schedules_group": null,
                "containers_group": null,
                "mbl_copy": null,
                "debit_note": null,
                "vessel": "V123",
                "booking_confirmed": 0,
                "arrival_notice_confirmed": 0,
                "freight_released_processed": 0,
                "customs_processed": 0,
                "DO_confirmed": 0,
                "freight_confirmed": 0,
                "customs_released": 0,
                "pending_refund": 0,
                "delivered": 0,
                "billed": 0,
                "cancelled": 0,
                "shipment_left": 0,
                "terminal_id": 5,
                "arrival_notice": 0,
                "cloned_from": null,
                "trucker_id": 2,
                "trucker_custom_note": null,
                "delivery_order_left": 0,
                "copy_customer": 1,
                "memo_customer": null,
                "suppliers_group_bookings": null,
                "containers_group_bookings": null,
                "schedules_group_bookings": null,
                "mbl_shipper": null,
                "mbl_shipper_address": null,
                "mbl_shipper_phone_number": null,
                "mbl_consignee": null,
                "mbl_consignee_address": null,
                "mbl_consignee_phone_number": null,
                "mbl_notify": null,
                "mbl_notify_address": null,
                "mbl_notify_phone_number": null,
                "mbl_description": null,
                "mbl_marks": null,
                "booking_confirmed_at": null,
                "tracking_request_id": null,
                "entry_netchb_submitted": 0,
                "entry_netchb_no": null,
                "entry_netchb_date": null,
                "entry_data": null,
                "do_sent_at": null,
                "an_sent_at": null,
                "retry_tracking_request": 0,
                "suppliers_commercial_docs": null,
                "pier_pass_paid": 1,
                "discharged": 1,
                "driver_assigned_pickup": 0,
                "container_empty": 0,
                "container_empty_time": null,
                "container_empty_date": null,
                "asigned_driver_return": 0,
                "returned": 0,
                "trucker_container": "CONT123",
                "deliver_to": "Porbandar",
                "dispatch_schedule": "{\"id\":1662103753291,\"location_from\":5,\"last_free_date\":\"2022-09-06\",\"per_diem_date\":\"2022-09-30\",\"legs\":[{\"id\":1662103753291,\"schedule_id\":1662103753291,\"type\":\"Yard\",\"address\":\"Jamnagar port\",\"date\":\"2022-09-07\",\"time\":\"12:00\",\"driver\":94,\"chassis\":7,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-09-06\",\"to_time\":\"12:01\",\"arrival_at_pickup_location_date\":\"2022-09-06\",\"arrival_at_pickup_location_time\":\"12:00\",\"departure_from_pickup_location_date\":\"\",\"departure_from_pickup_location_time\":\"\",\"arrival_at_delivery_location_date\":\"2022-09-07\",\"arrival_at_delivery_location_time\":\"12:00\",\"departure_from_delivery_location_date\":\"\",\"departure_from_delivery_location_time\":\"\"},{\"id\":1662110952656,\"schedule_id\":1662103753291,\"type\":\"Empty Return\",\"address\":\"porbandar port\",\"date\":\"2022-09-11\",\"time\":\"12:59\",\"driver\":78,\"chassis\":7,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-09-10\",\"to_time\":\"12:59\",\"arrival_at_pickup_location_date\":\"2022-09-10\",\"arrival_at_pickup_location_time\":\"12:01\",\"departure_from_pickup_location_date\":\"\",\"departure_from_pickup_location_time\":\"\",\"arrival_at_delivery_location_date\":\"2022-09-11\",\"arrival_at_delivery_location_time\":\"00:00\",\"departure_from_delivery_location_date\":\"\",\"departure_from_delivery_location_time\":\"\"}]}",
                "container_weight": "555.00",
                "container_size_id": 3,
                "container_commodity": "Steel",
                "customer_po": "PO123",
                "last_free_date": "2022-09-06T00:00:00.000000Z",
                "dropped": 0,
                "fully_released": 1,
                "arrived": 1,
                "dropped_full": 0,
                "dropped_empty": 0,
                "pending_billing": 1,
                "completed": 0,
                "in_yard_full": 0,
                "container_type_id": 0,
                "address": null,
                "per_diem_date": "2022-09-30",
                "contacts": "[\"vtest@gmail.com\"]",
                "is_scheduled": 1,
                "container_size": {
                    "id": 3,
                    "name": "40HC",
                    "created_at": "2021-05-30T22:30:17.000000Z",
                    "updated_at": "2021-05-30T22:30:17.000000Z",
                    "length": null,
                    "width": null,
                    "height": null,
                    "dimension": null
                },
                "terminal": {
                    "id": 5,
                    "name": "Fenix Marine Services Los Angeles - Eagle Marine Services (Y257)",
                    "firms_code": "Y257",
                    "address": "APL Global Gateway South 614 Terminal Way, San Pedro, CA 90731",
                    "created_at": "2020-04-17T14:03:25.000000Z",
                    "updated_at": "2022-02-15T06:54:48.000000Z",
                    "gate_fee": 1,
                    "map_location": null,
                    "latitude": null,
                    "longitude": null
                },
                "customer": {
                    "id": 18,
                    "company_name": "Vivekcustomerty",
                    "address": null,
                    "phone": "1234567890",
                    "admin_user_id": null,
                    "created_at": "2022-08-12T19:14:37.000000Z",
                    "updated_at": "2022-08-30T05:01:23.000000Z",
                    "managers": null,
                    "sale_persons": null,
                    "emails": [
                        {
                            "email": "vivek@gmail.com"
                        }
                    ],
                    "requirements": null,
                    "credit_term_freight": null,
                    "ein": null,
                    "trucker_id": 2,
                    "delivery_address": null,
                    "central_customer_key": "MFBQW8ZB"
                },
                "carrier": {
                    "id": 2,
                    "name": "ggggggggf",
                    "carrier_type_id": 1,
                    "created_at": "2022-05-26T07:29:33.000000Z",
                    "updated_at": "2022-05-26T07:29:33.000000Z"
                },
                "dispatch": {
                    "id": 71,
                    "unique_id": "1662103753291",
                    "shipment_id": 96,
                    "terminal_id": 5,
                    "last_free_date": "2022-09-06",
                    "per_diem_date": "2022-09-30",
                    "created_at": "2022-09-16T04:30:42.000000Z",
                    "updated_at": "2022-09-16T04:30:42.000000Z",
                    "legs": [
                        {
                            "id": 56,
                            "unique_id": "1662103753291",
                            "schedule_unique_id": "1662103753291",
                            "is_first_leg": 1,
                            "type": "Yard",
                            "mode": "Dropped",
                            "address": "Jamnagar port",
                            "pickup_location": null,
                            "chassis_id": 7,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 71,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-09-06 12:01:00",
                            "arrival_at_pickup_location_date_time": "2022-09-06 12:00:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-09-07 12:00:00",
                            "arrival_at_delivery_location_date_time": "2022-09-07 12:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        },
                        {
                            "id": 57,
                            "unique_id": "1662110952656",
                            "schedule_unique_id": "1662103753291",
                            "is_first_leg": 0,
                            "type": "Empty Return",
                            "mode": "Dropped",
                            "address": "porbandar port",
                            "pickup_location": "Jamnagar port",
                            "chassis_id": 7,
                            "driver_id": 78,
                            "driver_status": "Pending",
                            "dispatch_id": 71,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-09-10 12:59:00",
                            "arrival_at_pickup_location_date_time": "2022-09-10 12:01:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-09-11 12:59:00",
                            "arrival_at_delivery_location_date_time": "2022-09-11 00:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        }
                    ]
                }
            }
        ],
        "completed": [
            {
                "id": 93,
                "po_num": null,
                "mbl_num": "MBL123",
                "type": null,
                "term": null,
                "customer_id": 18,
                "delivery_order_id": null,
                "shipment_status": null,
                "shifl_ref": "700093",
                "origin_country": null,
                "destination_country": null,
                "etd": null,
                "eta": "2022-08-25T00:00:00.000000Z",
                "custom_notes": null,
                "total_cbm": null,
                "total_kg": null,
                "total_cartons": null,
                "created_at": "2022-08-24T13:48:55.000000Z",
                "updated_at": "2022-08-24T15:32:19.000000Z",
                "carrier_id": 4,
                "custom_content": null,
                "suppliers_group": null,
                "schedules_group": null,
                "containers_group": null,
                "mbl_copy": null,
                "debit_note": null,
                "vessel": "V123",
                "booking_confirmed": 0,
                "arrival_notice_confirmed": 0,
                "freight_released_processed": 0,
                "customs_processed": 0,
                "DO_confirmed": 0,
                "freight_confirmed": 0,
                "customs_released": 0,
                "pending_refund": 0,
                "delivered": 0,
                "billed": 0,
                "cancelled": 0,
                "shipment_left": 0,
                "terminal_id": 9,
                "arrival_notice": 0,
                "cloned_from": null,
                "trucker_id": 2,
                "trucker_custom_note": null,
                "delivery_order_left": 0,
                "copy_customer": 1,
                "memo_customer": null,
                "suppliers_group_bookings": null,
                "containers_group_bookings": null,
                "schedules_group_bookings": null,
                "mbl_shipper": null,
                "mbl_shipper_address": null,
                "mbl_shipper_phone_number": null,
                "mbl_consignee": null,
                "mbl_consignee_address": null,
                "mbl_consignee_phone_number": null,
                "mbl_notify": null,
                "mbl_notify_address": null,
                "mbl_notify_phone_number": null,
                "mbl_description": null,
                "mbl_marks": null,
                "booking_confirmed_at": null,
                "tracking_request_id": null,
                "entry_netchb_submitted": 0,
                "entry_netchb_no": null,
                "entry_netchb_date": null,
                "entry_data": null,
                "do_sent_at": null,
                "an_sent_at": null,
                "retry_tracking_request": 0,
                "suppliers_commercial_docs": null,
                "pier_pass_paid": 1,
                "discharged": 1,
                "driver_assigned_pickup": 0,
                "container_empty": 0,
                "container_empty_time": null,
                "container_empty_date": null,
                "asigned_driver_return": 0,
                "returned": 0,
                "trucker_container": "C123445",
                "deliver_to": "Rajkot",
                "dispatch_schedule": "{\"legs\":[{\"id\":1661320648280,\"type\":\"Yard\",\"address\":\"NY yard\",\"date\":\"2022-08-27\",\"time\":\"09:00\",\"driver\":94,\"chassis\":17,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-08-26\",\"to_time\":\"09:00\",\"arrival_at_pickup_location_date\":\"2022-08-26\",\"arrival_at_pickup_location_time\":\"10:00\",\"departure_from_pickup_location_date\":null,\"departure_from_pickup_location_time\":null,\"arrival_at_delivery_location_date\":\"2022-08-27\",\"arrival_at_delivery_location_time\":\"11:00\",\"departure_from_delivery_location_date\":null,\"departure_from_delivery_location_time\":null,\"address_from\":\"Everport Terminal - Berth 233 (Y124)\"},{\"id\":1661325808084,\"type\":\"Customer\",\"address\":\"Customer warehouse\",\"date\":\"2022-08-29\",\"time\":\"09:00\",\"driver\":94,\"chassis\":17,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-08-28\",\"to_time\":\"09:00\",\"arrival_at_pickup_location_date\":\"2022-08-28\",\"arrival_at_pickup_location_time\":\"10:00\",\"departure_from_pickup_location_date\":null,\"departure_from_pickup_location_time\":null,\"arrival_at_delivery_location_date\":\"2022-08-29\",\"arrival_at_delivery_location_time\":\"10:00\",\"departure_from_delivery_location_date\":null,\"departure_from_delivery_location_time\":null,\"address_from\":\"Everport Terminal - Berth 233 (Y124)\"},{\"id\":1661326259024,\"type\":\"Empty Return\",\"address\":\"Back to port\",\"date\":\"2022-08-31\",\"time\":\"09:00\",\"driver\":94,\"chassis\":17,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-08-30\",\"to_time\":\"09:00\",\"arrival_at_pickup_location_date\":\"2022-08-30\",\"arrival_at_pickup_location_time\":\"10:00\",\"departure_from_pickup_location_date\":\"\",\"departure_from_pickup_location_time\":\"\",\"arrival_at_delivery_location_date\":\"2022-08-31\",\"arrival_at_delivery_location_time\":\"10:00\",\"departure_from_delivery_location_date\":\"\",\"departure_from_delivery_location_time\":\"\",\"address_from\":\"Everport Terminal - Berth 233 (Y124)\"}],\"location_from\":9,\"per_diem_date\":\"2022-09-30\"}",
                "container_weight": "555.00",
                "container_size_id": 2,
                "container_commodity": "Iron",
                "customer_po": "PO123",
                "last_free_date": null,
                "dropped": 0,
                "fully_released": 1,
                "arrived": 1,
                "dropped_full": 0,
                "dropped_empty": 0,
                "pending_billing": 1,
                "completed": 0,
                "in_yard_full": 0,
                "container_type_id": 0,
                "address": null,
                "per_diem_date": "2022-09-30",
                "contacts": "[\"viveksamani47@gmail.com\"]",
                "is_scheduled": 1,
                "container_size": {
                    "id": 2,
                    "name": "40",
                    "created_at": "2021-05-30T22:30:12.000000Z",
                    "updated_at": "2021-05-30T22:30:12.000000Z",
                    "length": null,
                    "width": null,
                    "height": null,
                    "dimension": null
                },
                "terminal": {
                    "id": 9,
                    "name": "Everport Terminal - Berth 233 (Y124)",
                    "firms_code": "Y124",
                    "address": "389 Terminal Way, San Pedro, CA 90731",
                    "created_at": "2020-04-22T06:06:58.000000Z",
                    "updated_at": "2022-02-15T05:59:49.000000Z",
                    "gate_fee": 1,
                    "map_location": null,
                    "latitude": null,
                    "longitude": null
                },
                "customer": {
                    "id": 18,
                    "company_name": "Vivekcustomerty",
                    "address": null,
                    "phone": "1234567890",
                    "admin_user_id": null,
                    "created_at": "2022-08-12T19:14:37.000000Z",
                    "updated_at": "2022-08-30T05:01:23.000000Z",
                    "managers": null,
                    "sale_persons": null,
                    "emails": [
                        {
                            "email": "vivek@gmail.com"
                        }
                    ],
                    "requirements": null,
                    "credit_term_freight": null,
                    "ein": null,
                    "trucker_id": 2,
                    "delivery_address": null,
                    "central_customer_key": "MFBQW8ZB"
                },
                "carrier": null,
                "dispatch": {
                    "id": 68,
                    "unique_id": null,
                    "shipment_id": 93,
                    "terminal_id": 9,
                    "last_free_date": null,
                    "per_diem_date": "2022-09-30",
                    "created_at": "2022-09-16T04:30:42.000000Z",
                    "updated_at": "2022-09-16T04:30:42.000000Z",
                    "legs": [
                        {
                            "id": 53,
                            "unique_id": "1661320648280",
                            "schedule_unique_id": null,
                            "is_first_leg": 1,
                            "type": "Yard",
                            "mode": "Dropped",
                            "address": "NY yard",
                            "pickup_location": null,
                            "chassis_id": 17,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 68,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-08-26 09:00:00",
                            "arrival_at_pickup_location_date_time": "2022-08-26 10:00:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-08-27 09:00:00",
                            "arrival_at_delivery_location_date_time": "2022-08-27 11:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        },
                        {
                            "id": 54,
                            "unique_id": "1661325808084",
                            "schedule_unique_id": null,
                            "is_first_leg": 0,
                            "type": "Customer",
                            "mode": "Dropped",
                            "address": "Customer warehouse",
                            "pickup_location": "NY yard",
                            "chassis_id": 17,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 68,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-08-28 09:00:00",
                            "arrival_at_pickup_location_date_time": "2022-08-28 10:00:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-08-29 09:00:00",
                            "arrival_at_delivery_location_date_time": "2022-08-29 10:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        },
                        {
                            "id": 55,
                            "unique_id": "1661326259024",
                            "schedule_unique_id": null,
                            "is_first_leg": 0,
                            "type": "Empty Return",
                            "mode": "Dropped",
                            "address": "Back to port",
                            "pickup_location": "Customer warehouse",
                            "chassis_id": 17,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 68,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-08-30 09:00:00",
                            "arrival_at_pickup_location_date_time": "2022-08-30 10:00:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-08-31 09:00:00",
                            "arrival_at_delivery_location_date_time": "2022-08-31 10:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        }
                    ]
                }
            },
            {
                "id": 96,
                "po_num": null,
                "mbl_num": "MBL123",
                "type": null,
                "term": null,
                "customer_id": 18,
                "delivery_order_id": null,
                "shipment_status": null,
                "shifl_ref": "700096",
                "origin_country": null,
                "destination_country": null,
                "etd": null,
                "eta": "2022-09-05T00:00:00.000000Z",
                "custom_notes": null,
                "total_cbm": null,
                "total_kg": null,
                "total_cartons": null,
                "created_at": "2022-09-02T15:25:34.000000Z",
                "updated_at": "2022-09-02T17:30:45.000000Z",
                "carrier_id": 2,
                "custom_content": null,
                "suppliers_group": null,
                "schedules_group": null,
                "containers_group": null,
                "mbl_copy": null,
                "debit_note": null,
                "vessel": "V123",
                "booking_confirmed": 0,
                "arrival_notice_confirmed": 0,
                "freight_released_processed": 0,
                "customs_processed": 0,
                "DO_confirmed": 0,
                "freight_confirmed": 0,
                "customs_released": 0,
                "pending_refund": 0,
                "delivered": 0,
                "billed": 0,
                "cancelled": 0,
                "shipment_left": 0,
                "terminal_id": 5,
                "arrival_notice": 0,
                "cloned_from": null,
                "trucker_id": 2,
                "trucker_custom_note": null,
                "delivery_order_left": 0,
                "copy_customer": 1,
                "memo_customer": null,
                "suppliers_group_bookings": null,
                "containers_group_bookings": null,
                "schedules_group_bookings": null,
                "mbl_shipper": null,
                "mbl_shipper_address": null,
                "mbl_shipper_phone_number": null,
                "mbl_consignee": null,
                "mbl_consignee_address": null,
                "mbl_consignee_phone_number": null,
                "mbl_notify": null,
                "mbl_notify_address": null,
                "mbl_notify_phone_number": null,
                "mbl_description": null,
                "mbl_marks": null,
                "booking_confirmed_at": null,
                "tracking_request_id": null,
                "entry_netchb_submitted": 0,
                "entry_netchb_no": null,
                "entry_netchb_date": null,
                "entry_data": null,
                "do_sent_at": null,
                "an_sent_at": null,
                "retry_tracking_request": 0,
                "suppliers_commercial_docs": null,
                "pier_pass_paid": 1,
                "discharged": 1,
                "driver_assigned_pickup": 0,
                "container_empty": 0,
                "container_empty_time": null,
                "container_empty_date": null,
                "asigned_driver_return": 0,
                "returned": 0,
                "trucker_container": "CONT123",
                "deliver_to": "Porbandar",
                "dispatch_schedule": "{\"id\":1662103753291,\"location_from\":5,\"last_free_date\":\"2022-09-06\",\"per_diem_date\":\"2022-09-30\",\"legs\":[{\"id\":1662103753291,\"schedule_id\":1662103753291,\"type\":\"Yard\",\"address\":\"Jamnagar port\",\"date\":\"2022-09-07\",\"time\":\"12:00\",\"driver\":94,\"chassis\":7,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-09-06\",\"to_time\":\"12:01\",\"arrival_at_pickup_location_date\":\"2022-09-06\",\"arrival_at_pickup_location_time\":\"12:00\",\"departure_from_pickup_location_date\":\"\",\"departure_from_pickup_location_time\":\"\",\"arrival_at_delivery_location_date\":\"2022-09-07\",\"arrival_at_delivery_location_time\":\"12:00\",\"departure_from_delivery_location_date\":\"\",\"departure_from_delivery_location_time\":\"\"},{\"id\":1662110952656,\"schedule_id\":1662103753291,\"type\":\"Empty Return\",\"address\":\"porbandar port\",\"date\":\"2022-09-11\",\"time\":\"12:59\",\"driver\":78,\"chassis\":7,\"mode\":\"Dropped\",\"completed\":true,\"from_date\":\"2022-09-10\",\"to_time\":\"12:59\",\"arrival_at_pickup_location_date\":\"2022-09-10\",\"arrival_at_pickup_location_time\":\"12:01\",\"departure_from_pickup_location_date\":\"\",\"departure_from_pickup_location_time\":\"\",\"arrival_at_delivery_location_date\":\"2022-09-11\",\"arrival_at_delivery_location_time\":\"00:00\",\"departure_from_delivery_location_date\":\"\",\"departure_from_delivery_location_time\":\"\"}]}",
                "container_weight": "555.00",
                "container_size_id": 3,
                "container_commodity": "Steel",
                "customer_po": "PO123",
                "last_free_date": "2022-09-06T00:00:00.000000Z",
                "dropped": 0,
                "fully_released": 1,
                "arrived": 1,
                "dropped_full": 0,
                "dropped_empty": 0,
                "pending_billing": 1,
                "completed": 0,
                "in_yard_full": 0,
                "container_type_id": 0,
                "address": null,
                "per_diem_date": "2022-09-30",
                "contacts": "[\"vtest@gmail.com\"]",
                "is_scheduled": 1,
                "container_size": {
                    "id": 3,
                    "name": "40HC",
                    "created_at": "2021-05-30T22:30:17.000000Z",
                    "updated_at": "2021-05-30T22:30:17.000000Z",
                    "length": null,
                    "width": null,
                    "height": null,
                    "dimension": null
                },
                "terminal": {
                    "id": 5,
                    "name": "Fenix Marine Services Los Angeles - Eagle Marine Services (Y257)",
                    "firms_code": "Y257",
                    "address": "APL Global Gateway South 614 Terminal Way, San Pedro, CA 90731",
                    "created_at": "2020-04-17T14:03:25.000000Z",
                    "updated_at": "2022-02-15T06:54:48.000000Z",
                    "gate_fee": 1,
                    "map_location": null,
                    "latitude": null,
                    "longitude": null
                },
                "customer": {
                    "id": 18,
                    "company_name": "Vivekcustomerty",
                    "address": null,
                    "phone": "1234567890",
                    "admin_user_id": null,
                    "created_at": "2022-08-12T19:14:37.000000Z",
                    "updated_at": "2022-08-30T05:01:23.000000Z",
                    "managers": null,
                    "sale_persons": null,
                    "emails": [
                        {
                            "email": "vivek@gmail.com"
                        }
                    ],
                    "requirements": null,
                    "credit_term_freight": null,
                    "ein": null,
                    "trucker_id": 2,
                    "delivery_address": null,
                    "central_customer_key": "MFBQW8ZB"
                },
                "carrier": {
                    "id": 2,
                    "name": "ggggggggf",
                    "carrier_type_id": 1,
                    "created_at": "2022-05-26T07:29:33.000000Z",
                    "updated_at": "2022-05-26T07:29:33.000000Z"
                },
                "dispatch": {
                    "id": 71,
                    "unique_id": "1662103753291",
                    "shipment_id": 96,
                    "terminal_id": 5,
                    "last_free_date": "2022-09-06",
                    "per_diem_date": "2022-09-30",
                    "created_at": "2022-09-16T04:30:42.000000Z",
                    "updated_at": "2022-09-16T04:30:42.000000Z",
                    "legs": [
                        {
                            "id": 56,
                            "unique_id": "1662103753291",
                            "schedule_unique_id": "1662103753291",
                            "is_first_leg": 1,
                            "type": "Yard",
                            "mode": "Dropped",
                            "address": "Jamnagar port",
                            "pickup_location": null,
                            "chassis_id": 7,
                            "driver_id": 94,
                            "driver_status": "Pending",
                            "dispatch_id": 71,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-09-06 12:01:00",
                            "arrival_at_pickup_location_date_time": "2022-09-06 12:00:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-09-07 12:00:00",
                            "arrival_at_delivery_location_date_time": "2022-09-07 12:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        },
                        {
                            "id": 57,
                            "unique_id": "1662110952656",
                            "schedule_unique_id": "1662103753291",
                            "is_first_leg": 0,
                            "type": "Empty Return",
                            "mode": "Dropped",
                            "address": "porbandar port",
                            "pickup_location": "Jamnagar port",
                            "chassis_id": 7,
                            "driver_id": 78,
                            "driver_status": "Pending",
                            "dispatch_id": 71,
                            "completed": 1,
                            "pickup_scheduled_date_time": "2022-09-10 12:59:00",
                            "arrival_at_pickup_location_date_time": "2022-09-10 12:01:00",
                            "departure_from_pickup_location_date_time": null,
                            "delivery_scheduled_date_time": "2022-09-11 12:59:00",
                            "arrival_at_delivery_location_date_time": "2022-09-11 00:00:00",
                            "departure_from_delivery_location_date_time": null,
                            "lat": null,
                            "long": null,
                            "created_at": "2022-09-16T04:30:42.000000Z",
                            "updated_at": "2022-09-16T04:53:31.000000Z"
                        }
                    ]
                }
            }
        ],
        "cancelled": []
    }
}