<?php

namespace App\Observers;

use App\Item;

class ItemObserver
{

    public function created(Item $item)
    {
        if($item->item_num == '' || $item->item_num === null){
            $prefix = 'ITE';
            $num_code = 2222000000 + $item->id;
            $item->item_num = $num_code;
            $item->save();
        }
        /*TODO: check or prevent existency conflict of the new auto gen number 
            what if the autogenerated number is already in records create by manual input
        */
    }


    public function updated(Item $item)
    {
        //
    }

    public function deleted(Item $item)
    {
        //
    }


    public function restored(Item $item)
    {
        //
    }

    public function forceDeleted(Item $item)
    {
        //
    }
}
